### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by AshrinJose**

### CODE REVIEW

**Comment by AshrinJose** [comment]
closed

**Comment by AshrinJose** [comment]
closes #2

**Review by AshrinJose — COMMENTED** [review]
closes #2

**Review by AshrinJose — COMMENTED** [review]
changes to config

**Review by AshrinJose — COMMENTED** [review]
closes #2

**Review by AshrinJose — COMMENTED** [review]
closed #4

**Review by AshrinJose — COMMENTED** [review]
closed #3

**Review by AshrinJose — COMMENTED** [review]
closed #3

**Review by AshrinJose — COMMENTED** [review]
closed #4

**Review by fazzaMmsApis — APPROVED** [review]

**Pull request merged**
